#!/usr/bin/env python3.
import sys
import requests
import json


def main():


    if (len(sys.argv) < 2) or (sys.argv[2] == 'help'):
        print(
            '''
            help - lista os comandos
            listar - mostra um one liner
            os comandos seguim essa ordem:
            ip comando
            exemplos:
            tarefa 54.242.200.201 listar
            '''
        )
        sys.exit()
        
    ip = sys.argv[1]
    endpoint = "http://" + ip +":5000"+"/tasks"


    if sys.argv[2] == 'listar':
        r = requests.get(endpoint)
        print(r.text)
        #get all tarefa



if __name__ == "__main__":
    main()

